### ISSUE TITLE
是否考虑兼容one-hub

### ISSUE THREAD

**Issue by Passerby1011** [DullJZ/ChannelMonitor#1]
他的数据库结构可能和oneapi不太一样，
https://github.com/MartialBE/one-hub

**Comment by DullJZ** [comment]
能否给一个channels数据表的sql文件（记得脱敏）

考虑在config.json中加入一个字段用于区分不同项目的数据库

**Comment by DullJZ** [comment]
看了一下one-hub的数据表结构，应该是兼容的，有遇到不兼容的报错信息吗
