### ISSUE TITLE
one-hub在TABLES`abilities`未删除不可用模型

### ISSUE THREAD

**Issue by LoveU3th** [DullJZ/ChannelMonitor#3]
热佬。有个bug反馈一下。
用one-hub的时候有个可用模型的TABLES `abilities`，内容如下图，当只删除TABLES `channels`中的不可用模型时，还要对应删除TABLES `abilities`中相应的模型，否则还会显示为可用，但实际请求到的都是不可用渠道。
![image](https://github.com/user-attachments/assets/afc8bc75-65f0-4842-b6bd-3006001556cd)

**Comment by DullJZ** [comment]
了解了，没用过one-hub所以不清楚，这两天适配一下

**Comment by DullJZ** [comment]
https://github.com/DullJZ/ChannelMonitor/tree/feature/%233

请测试该分支是否修复了问题

编译后的文件也附上
[build.zip](https://github.com/user-attachments/files/17879521/build.zip)

**Comment by LoveU3th** [comment]
> https://github.com/DullJZ/ChannelMonitor/tree/feature/%233
> 
> 请测试该分支是否修复了问题
> 
> 编译后的文件也附上 [build.zip](https://github.com/user-attachments/files/17879521/build.zip)

这两天手边没有电脑，佬能不能搞个测试版docker镜像呢

**Comment by DullJZ** [comment]
> > https://github.com/DullJZ/ChannelMonitor/tree/feature/%233
> > 请测试该分支是否修复了问题
> > 编译后的文件也附上 [build.zip](https://github.com/user-attachments/files/17879521/build.zip)
> 
> 这两天手边没有电脑，佬能不能搞个测试版docker镜像呢

dulljz/channel-monitor:feature3

**Comment by LoveU3th** [comment]
佬，我测试过了，有以下反馈：
1、可用模型的TABLES `abilities`中每个模型的是否启用指的是对应的渠道是否启用，单独修改这里为0不能禁用这个可用模型，硬删除打开可以删掉；
2、删除列表中不可用模型后，列表是修改了，但是进入管理页面没有变动，需要任意手动进行一次模型增删操作才能更新可用模型列表，应该是内部更新函数还需要调用一次。但one-hub源码不太明白逻辑在哪

**Comment by LoveU3th** [comment]
我对比过手动删除和channel-monitor删除的差异，也就是TABLES abilities和channels。也就是数据库ok的

**Comment by DullJZ** [comment]
测试结果：
1. 需要硬删除才能删除用户组可用模型
2. 硬删除效果通过测试
3. one-hub管理页面用户模型没有自动更新

TODO：
1. 软删除无效，只保留硬删除
2. 尝试调用one-hub更新模型的路由函数

**Comment by DullJZ** [comment]
目前测试下来，ChannelGroup仅在渠道更新和程序启动时Load
![QQ_1732519063474](https://github.com/user-attachments/assets/2bd7437c-1e41-42b2-acc8-c3442393fcf4)

后续考虑解决方案

**Comment by LoveU3th** [comment]
我曾经写了一个定时通过One-hub更新渠道模型列表的python代码。后来因为ck失效需要更新嫌麻烦弃用了。
佬能从模拟登陆保证ck，再post更新渠道这样思路走不

**Comment by DullJZ** [comment]
其实oneapi都有系统令牌，可以用系统令牌操作数据
测试过oneapi、newapi直接读写数据库可行，newapi的用户可用模型会同步更新

解决办法：
1. 给onehub提issue
2. 使用post形式让onehub更新

我这边可以临时做一个post的解决方案，需要填写baseurl和系统令牌

**Comment by DullJZ** [comment]
> 我曾经写了一个定时通过One-hub更新渠道模型列表的python代码。后来因为ck失效需要更新嫌麻烦弃用了。 佬能从模拟登陆保证ck，再post更新渠道这样思路走不

已更新代码，在更新数据库后，发送api请求添加“refresh”渠道，激活onehub更新函数

可以使用feature3代码测试一下，我本地测试没问题了

config.json
```json
{
    "oneapi_type": "onehub",
    "exclude_channel": [],
    "exclude_model": ["advanced-voice"],
    "models": ["gpt-3.5-turbo", "gpt-4o"],
    "force_models": false,
    "time_period": "1h",
    "db_type": "YOUR_DB_TYPE",
    "db_dsn": "YOUR_DB_DSN",
    "base_url": "http://localhost:3000",
    "system_token": "YOUR_SYSTEM_TOKEN"
}
```

**Comment by LoveU3th** [comment]
佬，测试反馈，可用，赞！！！
下一步就是并发测试搞起来了

**Comment by DullJZ** [comment]
好的，那我就合并分支了
